import { precacheAndRoute } from 'workbox-precaching';

declare let self: ServiceWorkerGlobalScope & {
  __WB_MANIFEST: any;
};

const swSelf = (self as any);

// Precache assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Handle Push Notifications
swSelf.addEventListener('push', (event: any) => {
  let data: any = { notification: { title: 'Scoutly AI', body: 'Novo sinal de prospecção capturado!' } };
  
  if (event.data) {
    try {
      data = event.data.json();
    } catch (e) {
      console.warn('Push payload was not JSON:', event.data.text());
      data = { notification: { title: 'Scoutly AI', body: event.data.text() } };
    }
  }

  const options = {
    body: data.notification.body,
    icon: '/pwa-192x192.png',
    badge: '/pwa-192x192.png',
    vibrate: [100, 50, 100],
    data: data.notification.data || { url: '/opportunities' }
  };

  event.waitUntil(
    swSelf.registration.showNotification(data.notification.title, options)
  );
});

// Handle Notification Click (Open PWA Tab)
swSelf.addEventListener('notificationclick', (event: any) => {
  event.notification.close();
  const urlToOpen = event.notification.data?.url || '/';

  event.waitUntil(
    swSelf.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients: any) => {
      // Check if there is already a window open
      for (let i = 0; i < windowClients.length; i++) {
        const client = windowClients[i];
        if (client.url.includes(urlToOpen) && 'focus' in client) {
          return client.focus();
        }
      }
      // If not, open a new window
      if (swSelf.clients.openWindow) {
        return swSelf.clients.openWindow(urlToOpen);
      }
    })
  );
});
